dataset_save_path: dataset/yelp/yelp-dataset.pth
benchmark_filename: ['trn', 'val', 'tst']
ITEM_ID_FIELD: item_id
USER_ID_FIELD: user_id
load_col:
    inter: [user_id, item_id]
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

